apiVersion: v1
kind: Service
metadata:
  name: jenkins-service-eip
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 
  externalIPs: 
    - 13.234.18.130    

